### PR TITLE
update fork with latest changes

### PR DESCRIPTION
**Pull request by simonperneel**

### CODE REVIEW

**Review by simonperneel — COMMENTED** [review]
looks good

**Comment by simonperneel** [comment]
Hi @ErikBjare. I'm sorry to bother you. 

The study will launch next week (ERC Disconnect) to the general public. We would also like to be able to use the macOS version of activitywatch. However, the build fails at the codesigning step because the apple personalID is not entered. What exactly is that ID? How can I enter it? 

I have already updated the fork so that it is along with the latest version of your fantastic piece of software!

Thanks in advance!

**Comment by ErikBjare** [comment]
@simonperneel You need to obtain an Apple Developer ID (costs money), create an application in their dev portal, and assign the required credentials to the CI secrets in your repo settings.

However, note that for Apple to approve your application, you probably have to rebrand the application to something else than just "ActivityWatch" (to inform Apple & users that your application is *not* the standard ActivityWatch). This is technically required by the MPL license too (note: I am not a lawyer), but I'm not gonna hassle you about that given you're just using it in a study.

**Comment by simonperneel** [comment]
@ErikBjare Thanks you very much for the clarification! I'm learning a lot. This is the website of the study: [https://digitaalwelzijn.ugent.be](https://digitaalwelzijn.ugent.be) (it is in dutch though). I will look at the MPL License rules. We certainly don't want to walk away with the credits of your program, but really use it as a tool for the study. 

It seems like a lot of hassle to create an apple developer id for that small adjustment to your application. Is it not possible to generate the dmg without codesigning?

If not, maybe we will omit the macOS option in our study, or use the standard activitywatch version.

Thanks!

**Comment by ErikBjare** [comment]
It is possible to build without codesigning, but due to restrictions Apple has put in place for non-codesigned applications on macOS it is likely to lead to severe bugs (in particular around the Accessibility permissions needed to get window titles).

What modifications have you applied to your custom build? Any reason not to use the default one?

**Comment by simonperneel** [comment]
@ErikBjare Okay, using my custom build without code signing doesn't seem an option then. 

Our custom build does not keep track of the window title (for privacy reasons in our study). With the exception of some websites that are tracked (Facebook, Instagram, news sites,...). 

Is it possible to use the default ActivityWatch without title tracking enabled? Then we will omit the tracking of these certain websites for the macOS users. 

Your help is appreciated! My PI will look to make a donation to ActivityWatch, but she is still investigating whether it is allowed directly from the project budget.

**Comment by ErikBjare** [comment]
Window title tracking can be disabled through config files in a post-installation step. However, it won't be respected on macOS due to an implementation detail (although I could fix that). But I guess that wouldn't let you capture certain websites etc as you want. 

Another option, as I've suggested before (but not sure why you opted not to), is to let it track everything locally but you build a tiny export/upload tool that strips out everything sensitive and only leaves the categories you're interested in.

Another option is that I build a custom version using the main ActivityWatch keys with window titles disabled. But that requires a bit of work on my part.

Where are the modifications you've made to ignore titles and only collect high-level descriptions?

**Comment by simonperneel** [comment]
Hi Erik,

Thank you for your answer.

My modifications for excluding the title and only keep track of certain websites are in here: [util.py](https://github.com/simonperneel/aw-watcher-window/blob/6a4b1679c06cedeaf0d950e3bdd662a58b97fe9d/aw_watcher_window/util.py) (don't mind my sketchy code)

I think that adapting config files after installation will be a bit difficult for the computer laymen in our study.

We can't do the second option because possibly sensitive information would be stored, which is not allowed by the privacy regulations for our study (despite that it is only stored locally).

A build of the default activitywatch without the title tracking disabled seems like the best option. But it requires indeed work from your side, for which we would rather give something in return. 

I will contact you further in DM on discord.

**Comment by simonperneel** [comment]
I tried to send you a message via Discord - but it couldn't be delivered, because we are not connected. Can you add me 😄? SimonP Mict#8627

**Pull request merged**
