### PR TITLE
update submodules to fix node-ipc version

### PR DESCRIPTION
**Pull request by ErikBjare**
https://github.com/ActivityWatch/aw-webui/issues/330

### CODE REVIEW

**Comment by simonperneel** [comment]
Updated Github CI

**Comment by ErikBjare** [comment]
Looks like the builds are passing, you might want to merge this PR asap before I throw more commits on the upstream master branch :)

**Comment by simonperneel** [comment]
Hahaha I will! Thank you very much for the help, I will now try the release on my windows computer :)

**Comment by ErikBjare** [comment]
The macOS build isn't passing due to a CI issue where it can't find any configured keys to use for codesigning. If you want some sort of reasonable macOS release that's something you'll have to figure out (you could maybe use ours, but the macOS support is kinda spotty atm anyway...).

**Comment by simonperneel** [comment]
Yeah, I thought I would need still to configure some things for the macOS build. But the macOS version is not really necessary, I think all of our participants in the study will use Windows anyways

**Pull request merged**
